//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelBDContainer : DbContext
    {
        public ModelBDContainer(): base("name=ModelBDContainer")
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Proprietate> Proprietati { get; set; }
    }
}
