//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public Photo()
        {
            this.Proprietates = new HashSet<Proprietate>();
        }
        public Photo(String path, DateTime data_creare, String descriere = "")
        {
            this.Proprietates = new HashSet<Proprietate>();
          
            
                this.Proprietates = new HashSet<Proprietate>();
                this.Path = path;
                Data_creare = data_creare;
                Descriere = descriere;
                Deleted = false;
            
        }
    
        public int PhotoId { get; set; }
        public string Path { get; set; }
        public System.DateTime Data_creare { get; set; }
        public string Descriere { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proprietate> Proprietates { get; set; }
    }
}
